config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def new
    @flat = Flat.new
  end

  def show
    @flat = Flat.find(params[:id])
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<nav class="navbar navbar-light bg-light justify-content-between p-3">
  <a class="navbar-brand">Simple Airbnb</a>
  <form class="form-inline">
    <%= link_to "Add Flat", new_flat_path, class:"btn btn-outline-success my-2 my-sm-0" %>
    <!-- <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Add Flat</button> -->
  </form>
</nav>
<div class="container">
<h2>All our Flats (<%=@flats.count%>)</h2>
<ul>
  <% @flats.each do |flat| %>
<div class="d-inline-flex">
  <div class="card" style="width: 18rem;" >
    <img class="card-img-top" src="..." alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title"><%= flat.name%></h5>
      <p class="card-text"><%= flat.address%></p>
      <div class="d-flex justify-content-around">
      <p class="card-text"><i class="material-icons">people</i><%= flat.number_of_guests%></p>
      <p class="card-text"><i class="material-icons">euro_symbol</i><%= flat.price_per_night%></p>
      </div>
      <br>
      <br>
      <%= link_to "More info", flat_path(flat), class:"btn btn-primary" %>
    </div>
  </div>
</div>

  <% end %>
</ul>
</div>

app/views/flats/new.html.erb
<h2>Add flat</h2>
<%= simple_form_for (@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Add flat", class: "btn btn-primary" %>
<% end %>

app/views/flats/show.html.erb
<nav class="navbar navbar-light bg-light justify-content-between p-3">
  <a class="navbar-brand">Simple Airbnb</a>
  <form class="form-inline">
    <%= link_to "Add Flat", new_flat_path, class:"btn btn-outline-success my-2 my-sm-0" %>
  </form>
</nav>

<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1>Light &amp; <%= @flat.name %></h1>
        <p class="flat-show-address"><%= @flat.address %></p>
      </div>
      <div class="flat-show-card">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
        <div class="map" style="background-image: url('https://maps.googleapis.com/maps/api/staticmap?center=10 Clifton Gardens London W9 1DT&amp;zoom=13&amp;scale=2&amp;size=1000x1000&amp;maptype=roadmap&amp;markers=color:red%7C10 Clifton Gardens London W9 1DT&amp;key=AIzaSyBtaHK-BLhBg7TruJu8iKk_wETqZMJM-GY')"></div>
      </div>
    </div>

    <div class="col-4">
      <div class="flat-show-card">
        <h5>Book this place!</h5>

        <form action="">
          <div class="input-group">
            <span class="input-group-text" id="basic-addon1">From:</span>
            <input type="text" class="form-control" placeholder="12/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-text" id="basic-addon1">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class="flat-show-card">
        <h3>Details</h3>
        <div class="flex">
          <div class="flex">
            <i class="material-icons me-2">people</i><span><%= @flat.number_of_guests %></span>
          </div>
          <div class="flex ms-3">
            <i class="material-icons me-2">euro_symbol</i><%= @flat.price_per_night %>
          </div>
        </div>
      </div>
      <div class="flat-show-card">
        <div class="flex-align">
          <h6 class="no-mb">Share</h6>

          <div class="flex">
            <i class="fa fa-facebook-square fa-2x me-2"></i>
            <i class="fa fa-twitter-square fa-2x me-2"></i>
            <i class="fa fa-pinterest-square fa-2x me-2"></i>
            <i class="fa fa-envelope-square fa-2x"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Back to all flats', flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://kit.fontawesome.com/db4acf2644.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>